# Use a lightweight Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /base

# Copy shared requirements
COPY ./requirements.txt ./requirements.txt
# Install python-multipart globally in the base image
RUN pip install python-multipart

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set an environment variable for shared usage
ENV PYTHONUNBUFFERED=1
