apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indexing-service
  template:
    metadata:
      labels:
        app: indexing-service
    spec:
      containers:
      - name: indexing-service
        image: ashraf081/indexing-service:latest
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: indexing-service
spec:
  selector:
    app: indexing-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
